on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test
      - name: Test maze solving
        run: bash ./scripts/maze.sh
      - name: Test text matching
        run: python3 ./scripts/matching.py
